services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=portal'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=admin'
    ports:
      - '3306'
